
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9
      - image: circleci/postgres:13
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Set Up Virtual Environment
          command: |
            python -m venv env
            . env/bin/activate
      - run:
          name: Install Dependencies
          command: |
            . env/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . env/bin/activate
            python manage.py test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
