version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m venv env
            . env/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . env/bin/activate
            python manage.py test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
